

name: Scrape

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Scrape website
        run: |
          wget --mirror -p --html-extension --convert-links -r --no-if-modified-since -r -N -l inf  https://rediblesky.my.canva.site/home | true
          wget --mirror -p --html-extension --convert-links -r --no-if-modified-since -r -N -l inf -mkEpnp -e robots=off https://rediblesky.my.canva.site/home | true
          wget --mirror -p --html-extension --convert-links  https://rediblesky.my.canva.site/home | true
          cp -a ./rediblesky.my.canva.site/* .  &&  rm -rf rediblesky.my.canva.site | true
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
